---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - 'App Store'
  - 'System Settings'
  - Calendar
  - Contacts
  - FaceTime
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - TV

dockitems_persist:
  - name: "Safari"
    path: "/System/Cryptexes/App/System/Applications/Safari.app"
    pos: 2
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app"
    pos: 3
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app"
    pos: 4
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/FracKenA/dots.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/GitHub/dotfiles
dotfiles_files:
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - ansible-lint
  - awscli
  - azure-cli
  - chrome
  - gh
  - git
  - go
  - gpg
  - hashicorp/tap/consul
  - hashicorp/tap/nomad
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - hashicorp/tap/vault
  - helm
  - htop
  - httpie
  - iperf
  - kubernetes-cli
  - mas
  - nmap
  - openssl
  - pv
  - rclone
  - readline
  - ssh-copy-id
  - wget
  - zsh-completions
  - zsh-history-substring-search
  # - ansible # Installed via Pip.

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - dracula/install
  - hashicorp/tap
  # - homebrew/cask-driver
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - audacity
  - balenaetcher
  - betterdiscord-installer
  - betterdisplay
  - cakebrew
  - cheatsheet
  - chiaki
  - copilot-for-xcode
  - dash
  - discord
  - dracula-terminal
  - dracula-alfred
  - dracula-betterdiscord
  - dracula-gitkracken
  - dracula-insomnia
  - dracula-macos-color-picker
  - dracula-xcode
  - drawio
  - firefox
  - font-3270-nerd-font
  - font-agave-nerd-font
  - font-anonymice-nerd-font
  - font-arimo-nerd-font
  - font-aurulent-sans-mono-nerd-font
  - font-bigblue-terminal-nerd-font
  - font-bitstream-vera-sans-mono-nerd-font
  - font-blex-mono-nerd-font
  - font-caskaydia-cove-nerd-font
  - font-code-new-roman-nerd-font
  - font-cousine-nerd-font
  - font-daddy-time-mono-nerd-font
  - font-dejavu-sans-mono-nerd-font
  - font-droid-sans-mono-nerd-font
  - font-fantasque-sans-mono-nerd-font
  - font-fira-code-nerd-font
  - font-fira-mono-nerd-font
  - font-go-mono-nerd-font
  - font-gohufont-nerd-font
  - font-hack-nerd-font
  - font-hasklug-nerd-font
  - font-heavy-data-nerd-font
  - font-hurmit-nerd-font
  - font-im-writing-nerd-font
  - font-inconsolata-go-nerd-font
  - font-inconsolata-lgc-nerd-font
  - font-inconsolata-nerd-font
  - font-iosevka-nerd-font
  - font-jetbrains-mono-nerd-font
  - font-lekton-nerd-font
  - font-liberation-nerd-font
  - font-meslo-lg-nerd-font
  - font-monofur-nerd-font
  - font-monoid-nerd-font
  - font-mononoki-nerd-font
  - font-mplus-nerd-font
  - font-noto-nerd-font
  - font-open-dyslexic-nerd-font
  - font-overpass-nerd-font
  - font-profont-nerd-font
  - font-proggy-clean-tt-nerd-font
  - font-roboto-mono-nerd-font
  - font-sauce-code-pro-nerd-font
  - font-shure-tech-mono-nerd-font
  - font-space-mono-nerd-font
  - font-terminess-ttf-nerd-font
  - font-tinos-nerd-font
  - font-ubuntu-mono-nerd-font
  - font-ubuntu-nerd-font
  - font-victor-mono-nerd-font
  - github
  - gitkraken
  - handbrake
  - insomnia
  - iterm2
  - jetbrains-toolbox
  - launchpad-manager
  - licecap
  - logitech-g-hub
  - macdown
  - microsoft-azure-storage-explorer
  - microsoft-edge
  - microsoft-office
  - microsoft-remote-desktop
  - microsoft-teams
  - mosaic
  - mqtt-explorer
  - obs
  - openlens
  - orion
  - parallels
  - parsec
  - podman-desktop
  - powershell
  - rustdesk
  - sequel-ace
  - slack
  - steam
  - tor-browser
  - visual-studio-code
  - warp
  - wireshark
  - zoom
  # - docker
  # - goland
  # - pycharm

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1458969831, name: "JSON Peep for Safari" }
  - { id: 1543143740, name: "AdGuard Home Remote"}
  - { id: 1569813296, name: "1Password for Safari"}
  - {id: 1541862561, name: "FireShot Web Page Screenshots"}
  - {id: 408981434, name: "iMovie"}
  - {id: 409183694, name: "Keynote"}
  - {id: 409201541, name: "Pages"}
  - {id: 409203825, name: "Numbers"}
  - {id: 682658836, name: "GarageBand"}
  # - friendly streaming
  # - disk space analyzer
  # - azure VPN
    #  - { id: , name: "" }

mas_signin_dialog: false
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
