- name: Configure my Mac
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/config.yml"
      tags: ['always']
      # Include playbook configuration file using 'include_vars' module.

  tasks:
    - name: Install roles with common conditions.
      ansible.builtin.include_role:
        name: "{{ item.role }}"
        apply:
          tags: "{{ item.tags }}"
      when: item.when is defined and item.when
      loop:
        - { role: elliotweiser.osx-command-line-tools, tags: [] }
        - { role: geerlingguy.mac.homebrew, tags: ['homebrew'] }
        - { role: geerlingguy.dotfiles, tags: ['dotfiles'], when: configure_dotfiles }
        - { role: geerlingguy.mac.mas, tags: ['mas'], when: mas_installed_apps or mas_installed_app_ids }
        - { role: geerlingguy.mac.dock, tags: ['dock'], when: configure_dock }
        # Install roles based on conditions and tags.

    - name: Run sudoers, terminal, osx, extra-packages, git clone tasks.
      ansible.builtin.include_tasks: tasks/{{ item }}.yml
      when: vars[item]
      loop:
        - sudoers
        - terminal
        - osx
        - extra-packages
        - git-clone
      tags: ['{{ item }}']
      # Include task files based on conditions and tags.

    - name: Run configured post-provision ansible task files.
      ansible.builtin.include_tasks: "{{ outer_item }}"
      loop: "{{ post_provision_tasks | default([]) }}"
      loop_control:
        loop_var: outer_item
      tags: ['post']
      # Include post-provision task files based on the provided list.
