---
# Clone repos locally
- name: Clone Dracula Theme for iterm2
  ansible.builtin.git:
    repo: https://github.com/dracula/iterm.git
    dest: ~/.profile/iterm2/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for vscode
  ansible.builtin.git:
    repo: https://github.com/dracula/visual-studio-code.git
    dest: ~/.profile/vscode/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for vim
  ansible.builtin.git:
    repo: https://github.com/dracula/vim.git
    dest: ~/.profile/vim/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for terminal
  ansible.builtin.git:
    repo: https://github.com/dracula/terminal-app.git
    dest: ~/.profile/terminal/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for zsh
  ansible.builtin.git:
    repo: https://github.com/dracula/zsh.git
    dest: ~/.profile/zsh/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for visual studio
  ansible.builtin.git:
    repo: https://github.com/dracula/visual-studio
    dest: ~/.profile/visual-studio/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme wallpapers
  ansible.builtin.git:
    repo: https://github.com/dracula/wallpaper.git
    dest: ~/.profile/wallpaper/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for sequel pro
  ansible.builtin.git:
    repo: https://github.com/dracula/sequel-pro.git
    dest: ~/.profile/sequel-pro/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for zsh syntax highlighting
  ansible.builtin.git:
    repo: https://github.com/dracula/zsh-syntax-highlighting.git
    dest: ~/.profile/zsh-syntax-highlighting/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for macdown
  ansible.builtin.git:
    repo: https://github.com/dracula/macdown.git
    dest: ~/.profile/macdown/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for git
  ansible.builtin.git:
    repo: https://github.com/dracula/git.git
    dest: ~/.profile/git/
    clone: true
    update: true
    version: HEAD # noqa: latest

- name: Clone Dracula Theme for warp
  ansible.builtin.git:
    repo: https://github.com/dracula/warp.git
    dest: ~/.profile/warp/
    clone: true
    update: true
    version: HEAD # noqa: latest
